### ISSUE TITLE
Add support for default methods

### ISSUE THREAD

**Issue by AnatoliyYakimov** [pavel-grigorev/spring-icomponent#2]
Hello, Pavel! Im using this great library in my project, it works like a charm. But was a little bit confused when realize that i cannot use interface default methods with this library like JpaRepository does. Seems like we could easily fix this. I will try to create fix by myself in my spare time. I hope that this project still supported and i wuold be able to merge my PR.

**Comment by pavel-grigorev** [comment]
Hello Anatoly! Thanks for taking time and opening the PR. Will take a look ASAP!

**Comment by pavel-grigorev** [comment]
v1.1.0 is out! @AnatoliyYakimov thanks again for your contribution.
